name: Bug Report
description: Report a bug to help us improve Cinephage
title: '[Bug]: '
labels: ['Type: Bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the form below to help us investigate.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
        - label: I am using the latest version of Cinephage
          required: false

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of Cinephage is affected?
      options:
        - UI/Frontend
        - API/Backend
        - Indexers/Search
        - Download Clients
        - Library Management
        - Subtitles
        - Monitoring/Scheduler
        - Database
        - Docker/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (app crashes, data loss, security issue)
        - Major (feature broken, no workaround)
        - Minor (feature broken, workaround exists)
        - Cosmetic (visual issue, typo)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker
        - Docker Compose
        - Native (npm/node)
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (Debian/Ubuntu)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - Windows
        - macOS
        - Unraid
        - TrueNAS
        - Synology
        - Other NAS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Cinephage Version
      description: Version number or commit hash
      placeholder: 'e.g., 0.1.0 or abc1234'
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if UI issue)
      placeholder: 'e.g., Chrome 120, Firefox 121, Safari 17'

  - type: markdown
    attributes:
      value: |
        ### How to get logs

        **Log files location:**
        - Docker: `./logs/` (mapped from container's `/app/logs/`)
        - Native install: `logs/` in your Cinephage directory

        **Log files (attach the relevant ones to this issue):**
        - `main.log` - General application logs (always include this)
        - `indexers.log` - Indexer/search issues
        - `imports.log` - Download import issues
        - `streams.log` - Streaming issues
        - `monitoring.log` - Scheduler/automated task issues

        **How to retrieve:**
        ```bash
        # Docker Compose
        docker compose cp cinephage:/app/logs ./cinephage-logs

        # Native install
        # Logs are in the logs/ folder of your install directory
        ```

        Drag and drop the .log files below or paste the content.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Attach log files by dragging them here, or paste relevant excerpts. Always include main.log for backend issues.
      render: shell

  - type: textarea
    id: browser-logs
    attributes:
      label: Browser Console Logs (for UI issues)
      description: Open DevTools (F12) > Console tab, reproduce the issue, then paste any errors here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
